version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "Pipfile.lock" }}
            - v1-cache-
      - run:
          name: Install pip9, since pip10 have a regression https://github.com/pypa/pip/issues/5251
          command: pipenv install pip==9.0.3
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.v1-cache
      - run:
          name: run tests
          command: |
            pipenv run pytest