version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-browsers
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "Pipfile.lock" }}
            - v1-cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: v1-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: run tests
          command: |
            pipenv run pytest